### ISSUE TITLE
Tile "Bitmap.toImageResource()" enforce RGB_565 without possibility to change and keep alpha.

### ISSUE THREAD

**Issue by Tolriq** [google/horologist#2253] opened 2024-06-05 13:20 UTC
In accompanist Tile `Bitmap.toImageResource()` enforce RGB_565, took me quite some time to find that one, this force a black background on the image that are round cropped (`.transformations(CircleCropTransformation())` ) and of course as I did test with very dark images, I did not see the crop working and black background and searched around the source image.

![image](https://github.com/google/horologist/assets/932609/a3d4cb35-72f2-4ced-b2da-cede9d74359b)

The configuration should probably be a parameter as the doc is easy to miss and not very clear about why it's enforced.

**Comment by yschimke** [comment] 2024-06-05 13:24
I think dupe of https://github.com/google/horologist/issues/251

Valid request. Care to submit a PR, or otherwise review and test for me if not?

**Comment by yschimke** [comment] 2024-06-05 13:25
Let's continue on that other PR.

**Closed by yschimke** 2024-06-05 13:25 UTC
